### ISSUE TITLE
Unable to see the materials section on the Clump Properties

### ISSUE THREAD

**Issue by ZombieKillerGaming** [Al-Hydra/Blender-XFBIN-Importer#3]
![Screenshot_333](https://github.com/Al-Hydra/Blender-XFBIN-Importer/assets/106704341/6cdec55e-d0fb-4267-aa56-4b92a1a806ed)
It only shows Model Groups.

**Comment by Al-Hydra** [comment]
elaborate

**Comment by ZombieKillerGaming** [comment]
> elaborate

Sorry for the late reply, I thought it would notify me of a reply. I'm replacing Madara's model and the game will crash until I can have the clump recognize the materials of the xfbin. Under where it says Model Groups there's supposed to be a Materials section I can unhide but I don't see it. I know it exists because someone in the discord sent an image of their blender, and they had the materials option yet I somehow don't.

**Comment by Al-Hydra** [comment]
material properties have been moved to the materials tab in blender

**Comment by ZombieKillerGaming** [comment]
> material properties have been moved to the materials tab in blender

I see. Is that why the materials aren't recognized if swapping an older version of the plugin?
